version: '3.8'

services:
  db:
    image: mysql:5.7
    container_name: mysql
    restart: always
    environment:
      MYSQL_USER: mysql
      MYSQL_PASSWORD: 123456
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_DATABASE: flea_market
    ports:
    - 3306:3306
    volumes:
      - ./docker/db:/docker-entrypoint-initdb.d
